apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "fastapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
