image:
  repository: scala
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  database: postgres

fastapi:
  url: http://fastapi:8000/summarize

serviceAccount:
  create: true

resources: {}

autoscaling:
  enabled: false

ingress:
  enabled: false   # Set to true if you plan to expose it via Ingress
  className: ""
  annotations: {}
  hosts:
    - host: scala.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
