apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot.fullname" . }}
  labels:
    app: {{ include "springboot.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "springboot.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "springboot.name" . }}
    spec:
      containers:
        - name: springboot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SCALA_HOST
              value: "{{ .Values.scala.host }}"
            - name: SCALA_PORT
              value: "{{ .Values.scala.port }}"
