{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "springboot" }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
