apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scala.fullname" . }}
  labels:
    app: {{ include "scala.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "scala.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "scala.name" . }}
    spec:
      containers:
        - name: {{ include "scala.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_JDBC_URL
              value: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: FASTAPI_URL
              value: "{{ .Values.fastapi.url }}"
