apiVersion: v1
kind: Service
metadata:
  name: scala
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "scala.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
