apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-frontend.fullname" . }}
spec:
  selector:
    app: {{ include "react-frontend.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
