apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432